# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

before_install:
  - chmod +x mvnw

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на solomatoff.vyacheslav@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - solomatoff.vyacheslav@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="36292238-50e7-40b6-a57d-7190aa0772a3"

